# Generated by Django 4.0 on 2021-12-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
